export default {
  main: {
    widthMax: "100vw",
    heightMax: "100vh",
  },
  container: {
    margin: "0px 0px 0px 0px",
    width: "100%",
    float: "left",
    display: "flex",
    justifyContent: "space-between",
    marginTop: "-11px",
  },
  containerCenter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  containerTop: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "space-around",
    alignItems: "center",
    width: "100%",
    height: "60%",
    marginTop: "20px",
  },
  containerTop2: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    width: "30%",
    height: "100vh",
    marginTop: "10px",
    backgroundColor: "#FFC107",
  },
  contentLeft: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    width: "60%",
    height: "100vh",
    marginTop: "0",
    backgroundColor: "#FFC107",
  },
  contentRight: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    width: "40%",
    marginTop: "0",
    backgroundColor: "#FFFFFF",
  },
  contentLeft2: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-start",
    width: "30%",
    height: "100vh",
    marginTop: "0",
    backgroundColor: "#FFC107",
  },
  contentRight2: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    marginLeft: "40px",
    width: "60%",
    marginTop: "15px",
    backgroundColor: "#FFFFFF",
  },
  contentRight3: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    width: "40%",
    marginTop: "0",
    backgroundColor: "#FFFFFF",
  },
  left: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    width: "100%",
    height: "20%",
    marginTop: "40px",
  },
  separator: {
    width: "100%",
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
  },
  separator2: {
    width: "40%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "red",
  },
  perfil: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-around",
    marginTop: "10%",
  },
  perfil2: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    justifyContent: "space-around",
  },
};
