export default {
  menuUl: {
    margin: "0px",
    backgroundColor: "rgb(255, 90, 0)",
    left: "0px",
    top: "0px",
    marginRight: "auto",
    marginLeft: "auto",
    paddingRight: "10px",
    paddingLeft: "10px",
  },
  menuBody:{
    margin: "0",
  },
  menuLi:{
    display: "inline",
  },
  menuLogoLi:{
    display: "flex",
    float: "left",
  },
  logo:{
    width: "100px",
  },
  menuContainerLogo:{
    position: "relative",
    height: '100%',
    margin: "0 auto",
    maxWidth: "1280px",
    textAlign: "right",
    width: '65%',
  },
  menuContainer:{
    position: "relative",
    height: '100%',
    margin: "0 auto",
    maxWidth: "1280px",
    textAlign: "right",
    width: '65%',
    padding: '1%',
  },
  menuLogo:{
    textAlign: "left",
  },
  menuLink:{ 
    fontFamily: "Raleway",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "15px",
    lineHeight: "29px",    
    color: '#FFFFFF',
    textDecoration: "none",
    display: "inline",
    margin: "15px",
  },
  menuAcesso:{
    fontFamily: "Raleway",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: "15px",
    lineHeight: "29px",    
    color: '#FFFFFF',
    textDecoration: "none",
    display: "inline",
    position: "absolute",
    width: '10%',
    border: "1px solid #FFFFFF",
    boxSizing: "border-box",
    textAlign: "center",
  }
}
