export default {
  information: {
    float: "left",
    width: '60%',
    display: "inline",    
  },
  container:{
    margin: "0px 0px 0px 0px",
  },
  containerInfor:{

  },
  textInfor: {
    textAlign: "center",
    marginTop: '30%',
    fontFamily: "Raleway",
    fontStyle: "normal",
    fontWeight: "300",
    fontSize: "45px",
    lineHeight: "41px",
    color: "rgb(255, 61, 0)",
  },
  formRegistre:{
    float: "right",  	
    width: '40%', 	
    background: "#FFC107",  
  },
  form:{
    borderRadius: "5px",
    padding: "20px",
  },
  formTitle:{
    color: '#FFFFFF',
    textAlign: "center",
    fontSize: "40px",
  },
  inputCadastro100: {
    width: '100%',
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    borderRadius: "4px",
    boxSizing: "border-box",
  },
  inputCadastro40: {
    width: '40%',
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    borderRadius: "4px",
    boxSizing: "border-box",
  },
  inputCadastro45: {
    width: '45%',
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    borderRadius: "4px",
    boxSizing: "border-box",
  },
  inputCadastro45s: {
    width: '45%',
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    borderRadius: "4px",
    boxSizing: "border-box",
    marginLeft: "55px",
  },
  inputCadastro55: {
    width: '55%',
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    borderRadius: "4px",
    boxSizing: "border-box",
    marginLeft: "25px",
  },
  inputCadastro45: {
    width: '45%',
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    borderRadius: "4px",
    boxSizing: "border-box",
  },
  inputCadastro50: {
    width: '50%',
    padding: "12px 20px",
    margin: "8px 0",
    display: "inline-block",
    border: "1px solid #ccc",
    borderRadius: "4px",
    boxSizing: "border-box",
    marginLeft: "25px",
  },
  registerButton:{
    backgroundColor: "#FF5A00", /* Green */
    border: "none",
    color: "white",
    padding: "15px 32px",
    textAlign: "center",
    textDecoration: "none",
    display: "inline-block",
    fontSize: "16px",
    borderRadius: "10px",
   
  },
  containerButton:{
    textAlign: "center",
    marginTop: "50px",
  },
  containerCheck:{
    textAlign: "center",
    marginTop: "10px",
    marginBottom: "50px",
  }

}
